### ISSUE TITLE
Definition Profil Organisation / Location

### ISSUE THREAD

**Issue by alexzautke** [gematik/ISiK-Basismodul-Stufe-2#14]
Klarstellung notwendig ob Organisation / Location Profil benötigt wird im Zusammenhang mit Encounter Stufe 2

**Comment by ylboerner** [comment]
Hilfreich: 

https://www.hl7.org/fhir/valueset-location-physical-type.html

**Comment by alexzautke** [comment]
Slice mit MS für Encounter.location:
- Ward
- Bed
- Room

Open Slicing
Fixed Value auf .physicalType
1..1 auf location.identifier

Community Consulting ob Kodierung per HL7 oder SNOMED VS
.location lassen auf 0..* => Test in Titus erforderlich

**Comment by alexzautke** [comment]
Encounter.serviceProvider.identifier => 1..1

**Comment by alexzautke** [comment]
ISiK Stufe 2: Kein optionales Profil für Organization / Location
Abstimmung mit gematik Verzeichnisdienst notwendig, weitere Abstimmung in ISiK Stufe 3

**Comment by alexzautke** [comment]
Fixed by #25
