### ISSUE TITLE
Abbildung von stornierten Patienten

### ISSUE THREAD

**Issue by alexzautke** [gematik/ISiK-Basismodul-Stufe-2#15]
Derzeit haben wir keine Lösung, stornierte Patienten abzubilden. Patient.active ist nach längerer Diskussion als ungeeignet befunden worden.

**Comment by ylboerner** [comment]
Entweder Patient.active = false oder als gelöschter Patient. Eventuell enthält die FHIR Spec einen Hinweis bezüglich der Exklusion von Patient.active = false aus Suchanfragen. Dies sollte vorher geprüft werden.

**Comment by ylboerner** [comment]
Die FHIR Spezifikation besagt folgendes: 

_"Patientenakten können sich nur in einem von zwei Zuständen befinden: in Gebrauch (active=true) und nicht in Gebrauch (active=false). Ein normaler Datensatz ist aktiv, d. h. er ist in Verwendung. Active wird auf 'false' gesetzt, wenn ein Datensatz als Duplikat oder irrtümlich angelegt wird. Ein Datensatz muss nicht verknüpft sein, um inaktiviert zu werden."_

Patient.active wird üblicherweise auch verwendet, um Patienten zu markieren, die schon länger nicht mehr mit der jeweiligen Organisation in Kontakt standen. Allerdings ist dies keine Vorgabe der FHIR Spezifikation. 

In jedem Fall sollten wir klären, was eine Stornierung des Patienten alles umfasst. Die Verwendung von Patient.active ist an diesem Punkt allerdings der wahrscheinlichste Kandidat.

**Comment by ylboerner** [comment]
Nach erneuter Besprechung wird der Patient gelöscht, da wir die Komplexität so niedriger halten können.
