### ISSUE TITLE
Festlegung von verpflichtenden Suchparametern für alle Ressourcen

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/ISiK-Basismodul-Stufe-2#4]
Parameters for all Ressources / Search Result Parameters festelegen.
http://hl7.org/fhir/search.html

Im Zuge dessen die Suchparameter _id und _profile auf die allgemeine Suchparameterseite umziehen und nicht mehr bei allen Datenobjekten einzeln aufführen.

**Comment by alexzautke** [comment]
Duplikat https://github.com/gematik/ISiK-Basismodul-Stufe-2/issues/6
