### ISSUE TITLE
Weiterentwicklung Fall

### ISSUE THREAD

**Issue by ylboerner** [gematik/ISiK-Basismodul-Stufe-2#54]
**ISiKKontaktGesundheitseinrichtung** 
- [x] ISiK-enc-1 abändern: "status='finished' and class = 'amb' implies period.start.exists()"
- [x] Neue Regel hinzufügen: "status='finished' and class equal 'imp' implies period.start.exists() and period.end.exists()"
- [x] ISiK-enc-2 aufspalten: 
  - 1. severity=error: status = planned implies period.exists.not()
  - 2. severity=warning: status = planned implies extension.where...
- [x] ISiK-enc-5 löschen
- [x] ISiK-enc-6 auf warning setzen
- [x] serviceType auf 0..1
  - Fachabteilungsschlüssel 1..1
  - Weiteren Slice mit erweitertem Fachabteilungsschlüssel 0..1 hinzufügen (binding: https://simplifier.net/basisprofil-de-r4/fachabteilungsschluesselerweitert)
  - Constraint auf serviceType: type equal einrichtungskontakt implies serviceType exists()
- [x] .diagnosis.use.DiagnoseVerpflichtend binding auf required setzen
- [x] constraint hinzufügen: status = 'finished' and type = 'Einrichtungskontakt' implies diagnosis.exists()
- [x] DiagnoseVerpflichtend umbenennen -> Diagnosetyp
- [x] DiagnoseOptional umbenennen -> Diagnosesubtyp
- [x] .account auf 0..* MS setzen
- [x] .hospitalization auf 0..1 MS setzen
- [x] hospitalization.admitSource auf 0..1 setzen
- [x] partOf constraint hinzufügen: type != 'Einrichtungskontakt' implies partof.exists()

**ISiKAbrechnungsfall**
- [x] identifier.Aufnahmenummer 1..1
- [x] coverage.extension.Abrechnungsart code auf coding abändern
- [x] coverage.coverage auf MS setzen
- [x] coverage.extension 1..1
- [x] coverage.extension.AbrechnungsArt 1..1
- [x] 'Abrechnungsdiagnose' drg-use extension abändern: extension.use (coding + Binding an DRG use) + extension.Referenz (auf Condition oder Procedure) Extensions bauen

**Comment by alexzautke** [comment]
* Coverage.type slicen + required Binding auf AMB/IMP

**Comment by alexzautke** [comment]
Encounter.diagnosis.use.coding:ConditionOptional: 0..1 -> 0..*

**Comment by alexzautke** [comment]
Krankenhaushauptdiagnose aus VS im Encounter raus?
