### ISSUE TITLE
Rolle des Codes 'hospital-main-diagnosis' aus ISiKDiagnosesubtyp klären

### ISSUE THREAD

**Issue by ylboerner** [gematik/ISiK-Basismodul-Stufe-2#58]
Es ist noch nicht klar ob der Code 'hospital-main-diagnosis' aus dem VS in Encounter.diagnosis.use (ISiKDiagnosesubtyp) entfernt werden sollte. Bitte klären und eventuell entfernen.

**Comment by alexzautke** [comment]
Siehe #69
