### ISSUE TITLE
Encounter.status = cancelled Erläuterung im IG hinzufügen

### ISSUE THREAD

**Issue by ylboerner** [gematik/ISiK-Basismodul-Stufe-2#70]
Encounter.status sollte für Cancelled eine Erklärung enthalten für das Szenario 'stationär -> ambulant'. In diesem Szenario wird ein neuer Encounter mit class='AMB' erstellt, die Dokumentation auf diesen übertragen und der alte Encounter (class = stationär) auf 'cancelled' gesetzt. Bitte einen Verweise auf die canonical 'abandoned' hinzufügen.

**Comment by alexzautke** [comment]
Als Kommentar in #12 hinzugefügt
